version: '3'

services:

  utils:
    image: minhbkpro/utils
    container_name: utils
    volumes:
      - .:/usr/src/www
    stdin_open: true
    tty: true

  selenium:
    image: selenium/hub:3.12.0-cobalt
    container_name: selenium
    ports:
      - 4444:4444

  chrome:
    image: selenium/node-chrome:3.12.0-cobalt
    container_name: chrome
    depends_on:
      - selenium
    environment:
      - HUB_HOST=selenium
      - HUB_PORT=4444
